import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowRight, BookOpen, Clock3 } from "lucide-react";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { articles } from "@/lib/content";

export function generateStaticParams() { return articles.map((article) => ({ slug: article.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const article = articles.find((item) => item.slug === slug); if (!article) return {}; return { title: article.title, description: article.description, alternates: { canonical: `/artigos/${article.slug}` }, openGraph: { type: "article", title: article.title, description: article.description, url: `/artigos/${article.slug}` } }; }

export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const articleIndex = articles.findIndex((item) => item.slug === slug); if (articleIndex < 0) notFound(); const article = articles[articleIndex]; const nextArticle = articles[(articleIndex + 1) % articles.length]; const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://foxsim.vercel.app";
  const schema = { "@context": "https://schema.org", "@type": "Article", headline: article.title, description: article.description, inLanguage: "pt-BR", author: { "@type": "Organization", name: "FOX SIM" }, publisher: { "@type": "Organization", name: "FOX SIM" }, mainEntityOfPage: `${siteUrl}/artigos/${article.slug}`, articleSection: article.category, wordCount: article.sections.reduce((sum, section) => sum + section.body.join(" ").split(" ").length, 0) };
  return <main><article className="article-page"><header className="article-hero"><div className="article-grid-bg" /><div className="shell article-hero-inner"><Breadcrumbs items={[{ label: "Início", href: "/" }, { label: "Artigos", href: "/artigos" }, { label: article.title }]} /><div className="article-label">{article.category}</div><h1>{article.title}</h1><p>{article.description}</p><div className="article-meta"><span><Clock3 size={16} /> {article.readTime} min de leitura</span><span><BookOpen size={16} /> Guia educacional</span></div></div></header>
    <div className="shell article-layout"><aside><Link href="/artigos"><ArrowLeft size={15} /> Todos os artigos</Link><nav aria-label="Neste artigo"><b>NESTE ARTIGO</b>{article.sections.map((section, index) => <a href={`#secao-${index + 1}`} key={section.title}>{String(index + 1).padStart(2, "0")} {section.title}</a>)}</nav><div><b>LEMBRETE</b><p>Para voo real, use publicações oficiais, manuais aprovados e instrução habilitada.</p></div></aside><div className="article-body"><p className="article-intro">{article.intro}</p>{article.sections.map((section, index) => <section id={`secao-${index + 1}`} key={section.title}><span>{String(index + 1).padStart(2, "0")}</span><h2>{section.title}</h2>{section.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</section>)}<div className="article-educational"><b>Sobre este conteúdo</b><p>Material educacional produzido pela FOX SIM para apoiar estudo e simulação. Procedimentos, regras e dados operacionais podem mudar; confirme sempre as fontes oficiais vigentes.</p></div></div></div>
    <footer className="next-article"><div className="shell"><span>PRÓXIMA LEITURA</span><Link href={`/artigos/${nextArticle.slug}`}><div><small>{nextArticle.category}</small><b>{nextArticle.title}</b></div><ArrowRight size={24} /></Link></div></footer><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /></article></main>;
}
