import type { Metadata } from "next";
import { LegalPage } from "@/components/LegalPage";
export const metadata: Metadata = { title: "Política de privacidade", description: "Como a FOX SIM trata preferências, progresso local e dados técnicos.", alternates: { canonical: "/politica-de-privacidade" } };
export default function PrivacyPage() { return <LegalPage eyebrow="PRIVACIDADE" title="Política de privacidade" description="Transparência sobre quais informações existem, por que são usadas e como você mantém o controle." path="/politica-de-privacidade" sections={[
  { title: "Escopo", paragraphs: ["Esta política descreve o funcionamento do portal FOX SIM. O site oferece conteúdo educacional, questões, simulados, Pomodoro e calculadoras sem exigir cadastro no lançamento inicial."] },
  { title: "Dados salvos no dispositivo", paragraphs: ["Progresso de aulas, respostas, resultados, sessões Pomodoro, meta e preferência de cookies são armazenados no LocalStorage do navegador. Esses dados permanecem no dispositivo e não são enviados pela aplicação a um banco de dados da FOX SIM."], bullets: ["Você pode apagar esses dados limpando os dados do site no navegador.", "Outro navegador ou dispositivo terá um histórico separado.", "Modo privado pode remover os dados ao encerrar a sessão."] },
  { title: "Dados técnicos de hospedagem", paragraphs: ["A infraestrutura de hospedagem pode processar endereço IP, agente do navegador, horários e registros técnicos necessários para segurança, entrega e diagnóstico. Esse tratamento segue as políticas do provedor de hospedagem."] },
  { title: "Publicidade e serviços externos", paragraphs: ["O Google AdSense não está ativo sem um identificador válido configurado pelo responsável. Se for ativado futuramente, a política e o mecanismo de consentimento deverão ser revistos antes da veiculação. Links externos seguem as políticas de seus próprios sites."] },
  { title: "Finalidades e segurança", paragraphs: ["As informações locais servem para personalizar o painel e manter continuidade de estudo. Aplicamos minimização de dados e não solicitamos credenciais, documentos, dados de saúde ou informações financeiras."] },
  { title: "Seus controles", paragraphs: ["Você pode recusar armazenamento não essencial no banner, limpar LocalStorage e bloquear recursos do navegador. Para relatar preocupação, use a página de contato sem publicar dados sensíveis."] },
  { title: "Alterações", paragraphs: ["A política pode ser atualizada quando funcionalidades, fornecedores ou requisitos aplicáveis mudarem. A data no topo identifica a versão vigente."] },
]} />; }
